// 构建信息生成脚本：把 manifest 版本号 + 当前时间写入 src/common/buildinfo.js
// 由 npm run build / npm run release 自动调用，产物会被打进 rpk。
const fs = require('fs');
const path = require('path');

const manifest = JSON.parse(
  fs.readFileSync(path.join(__dirname, '../src/manifest.json'), 'utf8')
);
const now = new Date();
const pad = (n) => String(n).padStart(2, '0');
const buildTime =
  now.getFullYear() + '-' + pad(now.getMonth() + 1) + '-' + pad(now.getDate()) +
  ' ' + pad(now.getHours()) + ':' + pad(now.getMinutes());

const content =
  '// AUTO-GENERATED by scripts/prebuild.js — do not edit\n' +
  "export const versionName = '" + manifest.versionName + "';\n" +
  "export const buildTime = '" + buildTime + "';\n";

fs.writeFileSync(path.join(__dirname, '../src/common/buildinfo.js'), content);
console.log('[prebuild] versionName=' + manifest.versionName + ' buildTime=' + buildTime);
